/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 _3DOffice.glb
*/

import React, { } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model6(props) {
  const { nodes, materials } = useGLTF('/_3DOffice.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[2.187, 1.862, -18.59]}>
        <group position={[-2.187, -1.862, 18.59]} rotation={[-Math.PI, 0, -Math.PI]}>
          <group position={[-1.245, 0.45, 20.55]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-0.002, -1.033, 0]}>
              <mesh geometry={nodes.Box330.geometry} material={materials.wood_2} position={[2.064, 0, -0.45]} scale={[0.937, 1, 1]} />
              <mesh geometry={nodes.Box331.geometry} material={materials.Ardoise} position={[2.066, 0.014, -0.433]} scale={[0.937, 1, 1]} />
              <mesh geometry={nodes.Box332.geometry} material={materials.wood_2} position={[1.032, 0, -0.45]} scale={[0.937, 1, 1]} />
              <mesh geometry={nodes.Box333.geometry} material={materials.Ardoise} position={[1.034, 0.014, -0.433]} scale={[0.937, 1, 1]} />
              <mesh geometry={nodes.Box334.geometry} material={materials.wood_2} position={[0, 0, -0.45]} scale={[0.937, 1, 1]} />
              <mesh geometry={nodes.Box335.geometry} material={materials.Ardoise} position={[0.002, 0.014, -0.433]} scale={[0.937, 1, 1]} />
              <mesh geometry={nodes.Box336.geometry} material={materials.wood_2} position={[-1.032, 0, -0.45]} scale={[0.937, 1, 1]} />
              <mesh geometry={nodes.Box337.geometry} material={materials.Ardoise} position={[-1.03, 0.014, -0.433]} scale={[0.937, 1, 1]} />
              <mesh geometry={nodes.Box338.geometry} material={materials.wood_2} position={[-2.064, 0, -0.45]} scale={[0.937, 1, 1]} />
              <mesh geometry={nodes.Box339.geometry} material={materials.Ardoise} position={[-2.062, 0.014, -0.433]} scale={[0.937, 1, 1]} />
            </group>
            <group position={[-2.601, 1.57, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Box340.geometry} material={materials.wood_2} position={[2.064, 0, -0.45]} scale={[0.937, 1, 1]} />
              <mesh geometry={nodes.Box341.geometry} material={materials.Ardoise} position={[2.066, 0.014, -0.433]} scale={[0.937, 1, 1]} />
              <mesh geometry={nodes.Box342.geometry} material={materials.wood_2} position={[1.032, 0, -0.45]} scale={[0.937, 1, 1]} />
              <mesh geometry={nodes.Box343.geometry} material={materials.Ardoise} position={[1.034, 0.014, -0.433]} scale={[0.937, 1, 1]} />
            </group>
            <group position={[2.601, -1.528, 0]} rotation={[0, 0, Math.PI / 2]}>
              <mesh geometry={nodes.Box344.geometry} material={materials.wood_2} position={[2.064, 0, -0.45]} scale={[0.937, 1, 1]} />
              <mesh geometry={nodes.Box345.geometry} material={materials.Ardoise} position={[2.066, 0.014, -0.433]} scale={[0.937, 1, 1]} />
              <mesh geometry={nodes.Box346.geometry} material={materials.wood_2} position={[1.032, 0, -0.45]} scale={[0.937, 1, 1]} />
              <mesh geometry={nodes.Box347.geometry} material={materials.Ardoise} position={[1.034, 0.014, -0.433]} scale={[0.937, 1, 1]} />
            </group>
            <mesh geometry={nodes['Desk-Stand'].geometry} material={materials.wood_2} position={[3.036, 0.295, -0.45]} />
            <mesh geometry={nodes.Wook_stand.geometry} material={materials.wood_2} position={[1.433, 0.925, 0.55]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
          </group>
          <group position={[-9.787, 0.45, 25.124]} rotation={[-Math.PI / 2, 0, 0]}>
            {/* <pointLight intensity={2.461} decay={2} distance={10} position={[2.1, -1.02, 1.65]} rotation={[-Math.PI, 0, -Math.PI]} /> */}
            <pointLight intensity={1.178} decay={2} distance={10} position={[8.6, 1.649, 1.21]} rotation={[-Math.PI, 0, -Math.PI]} />
            {/* <pointLight intensity={2.461} decay={2} distance={10} position={[2.044, 2.327, 1.515]} rotation={[-Math.PI, 0, -Math.PI]} /> */}
            <mesh geometry={nodes.Box317.geometry} material={materials.Marble} position={[1.588, -2.636, -0.45]} />
            <mesh geometry={nodes.Box318.geometry} material={materials.Marble} position={[1.588, -1.583, -0.45]} />
            <mesh geometry={nodes.Box319.geometry} material={materials.Marble} position={[1.588, -0.53, -0.45]} />
            <mesh geometry={nodes.Box320.geometry} material={materials.Marble} position={[1.588, 0.524, -0.45]} />
            <mesh geometry={nodes.Box321.geometry} material={materials.Marble} position={[1.588, 1.577, -0.45]} />
            <mesh geometry={nodes.Box322.geometry} material={materials.Marble} position={[1.588, 2.63, -0.45]} />
            <mesh geometry={nodes.Box323.geometry} material={materials.Marble} position={[1.054, 3.168, -0.45]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes.Box324.geometry} material={materials.Marble} position={[-0.003, 3.168, -0.45]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes.Box325.geometry} material={materials.Marble} position={[-1.059, 3.168, -0.45]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes.Box326.geometry} material={materials.Marble} position={[-0.003, 2.087, -0.45]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes.Box327.geometry} material={materials.Marble} position={[-1.059, 2.087, -0.45]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes.Box328.geometry} material={materials.Marble} position={[1.054, -3.168, -0.45]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes.Box329.geometry} material={materials.Marble} position={[-1.588, 2.63, -0.45]} />
            <mesh geometry={nodes['Desk-Entrance'].geometry} material={materials.Marble} position={[0.978, 0.382, -0.45]} />
          </group>
          <group position={[-9.51, 3.81, 25.17]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0.277, 2.054, -0.122]} scale={0.888}>
              <group position={[0.001, -0.001, 0.221]}>
                <mesh geometry={nodes.Cylinder004.geometry} material={materials.WhiteGold} position={[-0.001, 0, -1.517]} />
                <mesh geometry={nodes.Cylinder005.geometry} material={materials.BlackMat} position={[-0.001, 0, -1.508]} scale={0.256} />
              </group>
              <mesh geometry={nodes.Object012.geometry} material={materials.WhiteGold} position={[0, 0, -1.546]} rotation={[0, 0, -Math.PI / 3]} scale={1.271} />
              <mesh geometry={nodes.Sphere021.geometry} material={materials.LampGlass} position={[0, 0, -1.546]} rotation={[0, 0, -Math.PI / 3]} scale={1.271} />
              <mesh geometry={nodes.Sphere022.geometry} material={materials.LampGlass} position={[0.001, -0.002, -1.546]} rotation={[0, 0, -Math.PI / 3]} scale={0.433} />
            </group>
            <group position={[0.28, 1.086, 0.131]} scale={0.888}>
              <group position={[0.001, 0.001, 0.085]}>
                <mesh geometry={nodes.Cylinder008.geometry} material={materials.WhiteGold} position={[-0.001, 0, -1.517]} />
                <mesh geometry={nodes.Cylinder009.geometry} material={materials.BlackMat} position={[-0.001, 0, -1.508]} scale={0.256} />
              </group>
              <mesh geometry={nodes.Sphere018.geometry} material={materials.WhiteGold} position={[0, 0, -1.545]} scale={0.611} />
            </group>
            <group position={[0.28, 0.69, -0.304]} scale={0.888}>
              <group position={[0, -0.001, 0.186]}>
                <mesh geometry={nodes.Cylinder010.geometry} material={materials.WhiteGold} position={[-0.001, 0, -1.517]} />
                <mesh geometry={nodes.Cylinder011.geometry} material={materials.BlackMat} position={[-0.001, 0, -1.508]} scale={0.256} />
              </group>
              <mesh geometry={nodes.Object010.geometry} material={materials.WhiteGold} position={[0, 0, -1.546]} scale={0.635} />
              <mesh geometry={nodes.Sphere016.geometry} material={materials.LampGlass} position={[0, 0, -1.546]} scale={0.635} />
              <mesh geometry={nodes.Sphere017.geometry} material={materials.LampGlass} position={[0, 0.001, -1.546]} scale={0.216} />
            </group>
            <group position={[0.279, 0.3, 0.281]} scale={0.888}>
              <group position={[0.001, 0, 0.084]}>
                <mesh geometry={nodes.Cylinder012.geometry} material={materials.WhiteGold} position={[-0.001, 0, -1.517]} />
                <mesh geometry={nodes.Cylinder013.geometry} material={materials.BlackMat} position={[-0.001, 0, -1.508]} scale={0.256} />
              </group>
              <mesh geometry={nodes.Sphere014.geometry} material={materials.LampGlass} position={[0, 0, -1.545]} scale={0.611} />
              <mesh geometry={nodes.Sphere015.geometry} material={materials.LampGlass} position={[0, 0, -1.545]} scale={0.176} />
            </group>
            <group position={[0.279, 0.041, 0.478]} scale={0.888}>
              <group position={[0.002, 0, 0.065]}>
                <mesh geometry={nodes.Cylinder014.geometry} material={materials.WhiteGold} position={[-0.001, 0, -1.517]} />
                <mesh geometry={nodes.Cylinder015.geometry} material={materials.BlackMat} position={[-0.001, 0, -1.508]} scale={0.256} />
              </group>
              <mesh geometry={nodes.Object009.geometry} material={materials.WhiteGold} position={[0, 0, -1.546]} scale={0.512} />
              <mesh geometry={nodes.Sphere012.geometry} material={materials.LampGlass} position={[0, 0, -1.546]} scale={0.512} />
              <mesh geometry={nodes.Sphere013.geometry} material={materials.LampGlass} position={[0.001, 0, -1.546]} scale={0.175} />
            </group>
            <group position={[0.28, -0.307, 0.094]} scale={0.888}>
              <group position={[0.001, 0, 0.266]}>
                <mesh geometry={nodes.Cylinder016.geometry} material={materials.WhiteGold} position={[-0.001, 0, -1.517]} />
                <mesh geometry={nodes.Cylinder017.geometry} material={materials.BlackMat} position={[-0.001, 0, -1.508]} scale={0.256} />
              </group>
              <mesh geometry={nodes.Sphere010.geometry} material={materials.LampGlass} position={[0, 0, -1.544]} scale={1.503} />
              <mesh geometry={nodes.Sphere011.geometry} material={materials.LampGlass} position={[0, 0.001, -1.544]} scale={0.433} />
            </group>
            <group position={[0.28, -0.703, -0.276]} scale={0.888}>
              <group position={[0.001, 0.003, 0.119]}>
                <mesh geometry={nodes.Cylinder018.geometry} material={materials.WhiteGold} position={[-0.001, 0, -1.517]} />
                <mesh geometry={nodes.Cylinder019.geometry} material={materials.BlackMat} position={[-0.001, 0, -1.508]} scale={0.256} />
              </group>
              <mesh geometry={nodes.Object008.geometry} material={materials.WhiteGold} position={[0, 0, -1.544]} scale={0.785} />
              <mesh geometry={nodes.Sphere008.geometry} material={materials.LampGlass} position={[0, 0, -1.544]} scale={0.785} />
              <mesh geometry={nodes.Sphere009.geometry} material={materials.LampGlass} position={[0.001, 0, -1.544]} scale={0.267} />
            </group>
            <group position={[0.279, -1.175, -0.19]} scale={0.888}>
              <group position={[0.001, 0.001, 0.187]}>
                <mesh geometry={nodes.Cylinder020.geometry} material={materials.WhiteGold} position={[-0.001, 0, -1.517]} />
                <mesh geometry={nodes.Cylinder021.geometry} material={materials.BlackMat} position={[-0.001, 0, -1.508]} scale={0.256} />
              </group>
              <mesh geometry={nodes.Object007.geometry} material={materials.WhiteGold} position={[0, 0, -1.547]} scale={0.635} />
              <mesh geometry={nodes.Sphere006.geometry} material={materials.LampGlass} position={[0, 0, -1.547]} scale={0.635} />
              <mesh geometry={nodes.Sphere007.geometry} material={materials.LampGlass} position={[0, 0.001, -1.547]} scale={0.216} />
            </group>
            <group position={[0.28, 1.453, -0.367]} scale={0.888}>
              <group position={[0.001, 0.002, 0.317]}>
                <mesh geometry={nodes.Cylinder006.geometry} material={materials.WhiteGold} position={[-0.001, 0, -1.517]} />
                <mesh geometry={nodes.Cylinder007.geometry} material={materials.BlackMat} position={[-0.001, 0, -1.508]} scale={0.256} />
              </group>
              <mesh geometry={nodes.Object011.geometry} material={materials.WhiteGold} position={[0, 0, -1.547]} />
              <mesh geometry={nodes.Sphere019.geometry} material={materials.LampGlass} position={[0, 0, -1.547]} />
              <mesh geometry={nodes.Sphere020.geometry} material={materials.LampGlass} position={[-0.001, 0.002, -1.547]} scale={0.341} />
            </group>
            <group position={[0.279, -1.627, 0.37]} scale={0.888}>
              <group position={[0.001, 0.003, 0.313]}>
                <mesh geometry={nodes.Cylinder022.geometry} material={materials.WhiteGold} position={[-0.001, 0, -1.517]} />
                <mesh geometry={nodes.Cylinder023.geometry} material={materials.BlackMat} position={[-0.001, 0, -1.508]} scale={0.256} />
              </group>
              <mesh geometry={nodes.Object006.geometry} material={materials.WhiteGold} position={[0, 0, -1.544]} />
              <mesh geometry={nodes.Sphere004.geometry} material={materials.LampGlass} position={[0, 0, -1.544]} />
              <mesh geometry={nodes.Sphere005.geometry} material={materials.LampGlass} position={[-0.001, 0.002, -1.544]} scale={0.341} />
            </group>
            <group position={[0.28, -2.223, -0.122]} scale={0.888}>
              <group position={[0.001, -0.001, 0.221]}>
                <mesh geometry={nodes.Cylinder024.geometry} material={materials.WhiteGold} position={[-0.001, 0, -1.517]} />
                <mesh geometry={nodes.Cylinder025.geometry} material={materials.BlackMat} position={[-0.001, 0, -1.508]} scale={0.256} />
              </group>
              <mesh geometry={nodes.Object005.geometry} material={materials.WhiteGold} position={[0, 0, -1.546]} scale={1.271} />
              <mesh geometry={nodes.Sphere002.geometry} material={materials.LampGlass} position={[0, 0, -1.546]} scale={1.271} />
              <mesh geometry={nodes.Sphere003.geometry} material={materials.LampGlass} position={[0.002, 0, -1.546]} scale={0.433} />
            </group>
            <group position={[-0.484, 2.343, 0.281]} rotation={[0, 0, Math.PI / 2]} scale={0.888}>
              <group position={[0.001, 0, 0.084]}>
                <mesh geometry={nodes.Cylinder026.geometry} material={materials.WhiteGold} position={[-0.001, 0, -1.517]} />
                <mesh geometry={nodes.Cylinder027.geometry} material={materials.BlackMat} position={[-0.001, 0, -1.508]} scale={0.256} />
              </group>
              <mesh geometry={nodes.Sphere025.geometry} material={materials.LampGlass} position={[0, 0, -1.545]} scale={0.611} />
              <mesh geometry={nodes.Sphere026.geometry} material={materials.LampGlass} position={[0, 0, -1.545]} scale={0.176} />
            </group>
            <group position={[-0.116, 2.342, 0.478]} rotation={[0, 0, Math.PI / 2]} scale={0.888}>
              <group position={[0.002, 0, 0.065]}>
                <mesh geometry={nodes.Cylinder028.geometry} material={materials.WhiteGold} position={[-0.001, 0, -1.517]} />
                <mesh geometry={nodes.Cylinder029.geometry} material={materials.BlackMat} position={[-0.001, 0, -1.508]} scale={0.256} />
              </group>
              <mesh geometry={nodes.Object013.geometry} material={materials.WhiteGold} position={[0, 0, -1.546]} scale={0.512} />
              <mesh geometry={nodes.Sphere023.geometry} material={materials.LampGlass} position={[0, 0, -1.546]} scale={0.512} />
              <mesh geometry={nodes.Sphere024.geometry} material={materials.LampGlass} position={[0.001, 0, -1.546]} scale={0.175} />
            </group>
            <mesh geometry={nodes.Cylinder030.geometry} material={materials.BlackMat} position={[0.278, 2.052, -0.069]} scale={[0.449, 0.449, 1.579]} />
            <mesh geometry={nodes.Cylinder031.geometry} material={materials.BlackMat} position={[0.278, 1.456, -0.069]} scale={[0.449, 0.449, 1.579]} />
            <mesh geometry={nodes.Cylinder032.geometry} material={materials.BlackMat} position={[0.278, 1.085, -0.069]} scale={[0.449, 0.449, 1.579]} />
            <mesh geometry={nodes.Cylinder033.geometry} material={materials.BlackMat} position={[0.278, 0.69, -0.069]} scale={[0.449, 0.449, 1.579]} />
            <mesh geometry={nodes.Cylinder034.geometry} material={materials.BlackMat} position={[0.278, 0.3, -0.069]} scale={[0.449, 0.449, 1.579]} />
            <mesh geometry={nodes.Cylinder035.geometry} material={materials.BlackMat} position={[0.278, 0.04, -0.069]} scale={[0.449, 0.449, 1.579]} />
            <mesh geometry={nodes.Cylinder036.geometry} material={materials.BlackMat} position={[0.278, -0.308, -0.069]} scale={[0.449, 0.449, 1.579]} />
            <mesh geometry={nodes.Cylinder037.geometry} material={materials.BlackMat} position={[0.278, -0.699, -0.069]} scale={[0.449, 0.449, 1.579]} />
            <mesh geometry={nodes.Cylinder038.geometry} material={materials.BlackMat} position={[0.278, -1.175, -0.069]} scale={[0.449, 0.449, 1.579]} />
            <mesh geometry={nodes.Cylinder039.geometry} material={materials.BlackMat} position={[0.278, -1.624, -0.069]} scale={[0.449, 0.449, 1.579]} />
            <mesh geometry={nodes.Cylinder040.geometry} material={materials.BlackMat} position={[0.278, -2.223, -0.069]} scale={[0.449, 0.449, 1.579]} />
            <mesh geometry={nodes.Cylinder041.geometry} material={materials.BlackMat} position={[-0.114, 2.342, -0.069]} scale={[0.449, 0.449, 1.579]} />
            <mesh geometry={nodes.Cylinder042.geometry} material={materials.BlackMat} position={[-0.482, 2.342, -0.069]} scale={[0.449, 0.449, 1.579]} />
          </group>
          <mesh geometry={nodes.OrganiserBanner.geometry} material={materials['Booth white']} position={[0.755, 1.763, 20.209]} rotation={[Math.PI / 2, 0, 0]} scale={0.066} />
          <mesh geometry={nodes.OrganiserBanner_Background.geometry} material={materials['Booth white']} position={[0.755, 1.763, 20.2]} rotation={[Math.PI / 2, 0, 0]} scale={0.082} />
        </group>
        <group position={[-2.187, -1.862, 18.59]} rotation={[-Math.PI, 0, -Math.PI]}>
          <group position={[19.308, 2.233, 33.599]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[29.644, 1.29, 0.017]}>
              <mesh geometry={nodes['Barre-Porte-Ext'].geometry} material={materials['Menuiseries-GRIS']} position={[0.007, -0.022, 0.782]} scale={[1.031, 1, 1]} />
              <mesh geometry={nodes['Barre-Porte-Ext_1'].geometry} material={materials['Menuiseries-BEIGE']} position={[-1.4, -0.004, -2.25]} />
              <mesh geometry={nodes['Barre-Porte-Ext_2'].geometry} material={materials['Menuiseries-BEIGE']} position={[-1.531, -0.004, -2.25]} />
              <mesh geometry={nodes['Barre-Porte-Ext_3'].geometry} material={materials['Menuiseries-BEIGE']} position={[1.4, -0.004, -2.25]} />
              <mesh geometry={nodes['Barre-Porte-Ext_4'].geometry} material={materials['Menuiseries-BEIGE']} position={[1.531, -0.004, -2.25]} />
              <mesh geometry={nodes.Box192.geometry} material={materials['Menuiseries-GRIS']} position={[-1.531, -0.344, -2.25]} />
              <mesh geometry={nodes['Montants-Porte-EXT'].geometry} material={materials['Menuiseries-GRIS']} position={[-0.711, -0.196, -2.25]} />
              <mesh geometry={nodes['Montants-Porte-EXT_1'].geometry} material={materials['Menuiseries-GRIS']} position={[0.706, -0.196, -2.25]} rotation={[Math.PI, 0, 0]} scale={-1} />
              <mesh geometry={nodes['Poteau-Metal-EXT_39'].geometry} material={materials['Menuiseries-GRIS']} position={[1.402, -0.344, -2.25]} />
              <mesh geometry={nodes['Vitre-Porte-Ext'].geometry} material={materials.Glass} position={[0.009, -0.204, -2.25]} />
            </group>
            <group position={[10.582, 1.29, 0.017]}>
              <mesh geometry={nodes['Barre-Porte-Ext001'].geometry} material={materials['Menuiseries-BEIGE']} position={[1.531, -0.004, -2.25]} />
              <mesh geometry={nodes['Barre-Porte-Ext002'].geometry} material={materials['Menuiseries-BEIGE']} position={[1.4, -0.004, -2.25]} />
              <mesh geometry={nodes['Barre-Porte-Ext003'].geometry} material={materials['Menuiseries-BEIGE']} position={[-1.531, -0.004, -2.25]} />
              <mesh geometry={nodes['Barre-Porte-Ext004'].geometry} material={materials['Menuiseries-BEIGE']} position={[-1.4, -0.004, -2.25]} />
              <mesh geometry={nodes['Barre-Porte-Ext005'].geometry} material={materials['Menuiseries-GRIS']} position={[0.007, -0.022, 0.782]} scale={[1.031, 1, 1]} />
              <mesh geometry={nodes.Box193.geometry} material={materials['Menuiseries-GRIS']} position={[-1.531, -0.344, -2.25]} />
              <mesh geometry={nodes['Montants-Porte-EXT001'].geometry} material={materials['Menuiseries-GRIS']} position={[-0.711, -0.196, -2.25]} />
              <mesh geometry={nodes['Montants-Porte-EXT002'].geometry} material={materials['Menuiseries-GRIS']} position={[0.706, -0.196, -2.25]} rotation={[Math.PI, 0, 0]} scale={-1} />
              <mesh geometry={nodes['Poteau-Metal-EXT001'].geometry} material={materials['Menuiseries-GRIS']} position={[1.402, -0.344, -2.25]} />
              <mesh geometry={nodes['Vitre-Porte-Ext001'].geometry} material={materials.Glass} position={[0.009, -0.204, -2.25]} />
            </group>
            <group position={[-8.491, 1.29, 0.017]}>
              <mesh geometry={nodes['Barre-Porte-Ext006'].geometry} material={materials['Menuiseries-BEIGE']} position={[1.531, -0.004, -2.25]} />
              <mesh geometry={nodes['Barre-Porte-Ext007'].geometry} material={materials['Menuiseries-BEIGE']} position={[1.4, -0.004, -2.25]} />
              <mesh geometry={nodes['Barre-Porte-Ext008'].geometry} material={materials['Menuiseries-BEIGE']} position={[-1.531, -0.004, -2.25]} />
              <mesh geometry={nodes['Barre-Porte-Ext009'].geometry} material={materials['Menuiseries-BEIGE']} position={[-1.4, -0.004, -2.25]} />
              <mesh geometry={nodes['Barre-Porte-Ext010'].geometry} material={materials['Menuiseries-GRIS']} position={[0.007, -0.022, 0.782]} scale={[1.031, 1, 1]} />
              <mesh geometry={nodes.Box194.geometry} material={materials['Menuiseries-GRIS']} position={[-1.531, -0.344, -2.25]} />
              <mesh geometry={nodes['Montants-Porte-EXT003'].geometry} material={materials['Menuiseries-GRIS']} position={[-0.711, -0.196, -2.25]} />
              <mesh geometry={nodes['Montants-Porte-EXT004'].geometry} material={materials['Menuiseries-GRIS']} position={[0.706, -0.196, -2.25]} rotation={[Math.PI, 0, 0]} scale={-1} />
              <mesh geometry={nodes['Poteau-Metal-EXT002'].geometry} material={materials['Menuiseries-GRIS']} position={[1.402, -0.344, -2.25]} />
              <mesh geometry={nodes['Vitre-Porte-Ext002'].geometry} material={materials.Glass} position={[0.009, -0.204, -2.25]} />
            </group>
            <mesh geometry={nodes.Box130.geometry} material={materials['Default-Material']} position={[31.113, 1.264, -2.233]} />
            <mesh geometry={nodes.Box132.geometry} material={materials['Default-Material']} position={[28.179, 1.264, -2.233]} />
            <mesh geometry={nodes.Box182.geometry} material={materials['Menuiseries-GRIS']} position={[38.635, 1.575, -2.233]} />
            <mesh geometry={nodes['Cache-Vitre-EXT'].geometry} material={materials['Default-Material']} position={[34.513, 1.096, 1.934]} />
            <mesh geometry={nodes['EXT-Menuiserie'].geometry} material={materials['Default-Material']} position={[-16.085, 1.15, -2.233]} />
            <mesh geometry={nodes['EXT-Menuiserie001'].geometry} material={materials['Default-Material']} position={[-19.219, 1.15, -2.233]} />
            <mesh geometry={nodes['EXT-Menuiserie002'].geometry} material={materials['Menuiseries-ANTHRACITE']} position={[-21.361, 1.15, -2.233]} />
            <mesh geometry={nodes['EXT-Menuiserie003'].geometry} material={materials['Menuiseries-ANTHRACITE']} position={[-24.511, 1.15, -2.233]} />
            <mesh geometry={nodes['Menuiseries-EXT'].geometry} material={materials['Menuiseries-ANTHRACITE']} position={[-24.231, 1.109, -2.233]} rotation={[Math.PI, 0, 0.698]} scale={-1} />
            <mesh geometry={nodes['Menuiseries-EXT_1'].geometry} material={materials['Menuiseries-ANTHRACITE']} position={[-21.539, 1.057, -2.233]} rotation={[0, 0, 0.698]} />
            <mesh geometry={nodes['Menuiseries-EXT_2'].geometry} material={materials['Default-Material']} position={[-18.897, 1.094, -2.233]} rotation={[Math.PI, 0, 0.698]} scale={-1} />
            <mesh geometry={nodes['Menuiseries-EXT_3'].geometry} material={materials['Default-Material']} position={[-16.246, 1.057, -2.233]} rotation={[0, 0, 0.698]} />
            <mesh geometry={nodes.Object002.geometry} material={materials['CONCRETE SMOOTH']} position={[42.046, -1.508, -0.045]} />
            <mesh geometry={nodes.Object003.geometry} material={materials['CONCRETE SMOOTH']} position={[2.743, 29.273, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT'].geometry} material={materials['Menuiseries-GRIS']} position={[-29.053, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_1'].geometry} material={materials['Menuiseries-GRIS']} position={[-27.558, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_2'].geometry} material={materials['Menuiseries-GRIS']} position={[-26.091, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_3'].geometry} material={materials['Menuiseries-GRIS']} position={[-24.624, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_4'].geometry} material={materials['Menuiseries-GRIS']} position={[-15.824, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_5'].geometry} material={materials['Menuiseries-GRIS']} position={[-14.357, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_6'].geometry} material={materials['Menuiseries-GRIS']} position={[-12.89, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_7'].geometry} material={materials['Menuiseries-GRIS']} position={[-11.423, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_8'].geometry} material={materials['Default-Material']} position={[-9.957, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_9'].geometry} material={materials['Default-Material']} position={[-8.49, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_10'].geometry} material={materials['Default-Material']} position={[-7.023, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_11'].geometry} material={materials['Menuiseries-GRIS']} position={[-5.556, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_12'].geometry} material={materials['Menuiseries-GRIS']} position={[-4.09, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_13'].geometry} material={materials['Menuiseries-GRIS']} position={[-2.623, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_14'].geometry} material={materials['Menuiseries-GRIS']} position={[-1.156, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_15'].geometry} material={materials['Menuiseries-GRIS']} position={[0.311, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_16'].geometry} material={materials['Menuiseries-GRIS']} position={[1.778, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_17'].geometry} material={materials['Menuiseries-GRIS']} position={[3.244, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_18'].geometry} material={materials['Menuiseries-GRIS']} position={[4.711, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_19'].geometry} material={materials['Menuiseries-GRIS']} position={[6.178, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_20'].geometry} material={materials['Menuiseries-GRIS']} position={[7.645, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_21'].geometry} material={materials['Default-Material']} position={[9.111, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_22'].geometry} material={materials['Default-Material']} position={[10.578, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_23'].geometry} material={materials['Default-Material']} position={[12.045, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_24'].geometry} material={materials['Menuiseries-GRIS']} position={[13.512, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_25'].geometry} material={materials['Menuiseries-GRIS']} position={[14.978, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_26'].geometry} material={materials['Menuiseries-GRIS']} position={[16.445, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_27'].geometry} material={materials['Menuiseries-GRIS']} position={[17.912, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_28'].geometry} material={materials['Menuiseries-GRIS']} position={[19.379, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_29'].geometry} material={materials['Menuiseries-GRIS']} position={[20.845, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_30'].geometry} material={materials['Menuiseries-GRIS']} position={[22.312, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_31'].geometry} material={materials['Menuiseries-GRIS']} position={[23.779, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_32'].geometry} material={materials['Menuiseries-GRIS']} position={[25.246, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_33'].geometry} material={materials['Menuiseries-GRIS']} position={[26.712, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_34'].geometry} material={materials['Menuiseries-GRIS']} position={[32.664, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_35'].geometry} material={materials['Menuiseries-GRIS']} position={[34.131, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_36'].geometry} material={materials['Menuiseries-GRIS']} position={[35.598, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_37'].geometry} material={materials['Menuiseries-GRIS']} position={[37.064, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT_38'].geometry} material={materials['Menuiseries-GRIS']} position={[38.531, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT003'].geometry} material={materials['Menuiseries-GRIS']} position={[-19.318, 1.264, -2.233]} />
            <mesh geometry={nodes['Poteau-Metal-EXT004'].geometry} material={materials['Menuiseries-GRIS']} position={[-21.122, 1.264, -2.233]} />
            <mesh geometry={nodes['Toiture-Porte-EXT'].geometry} material={materials['CONCRETE SMOOTH']} position={[-30.323, 0.644, 1.644]} />
            <mesh geometry={nodes['Toiture-Porte-EXT_1'].geometry} material={materials['CONCRETE SMOOTH']} position={[-40.732, 0.581, 2.056]} />
            <mesh geometry={nodes['Toiture-Porte-EXT_2'].geometry} material={materials['CONCRETE SMOOTH']} position={[21.192, 0.644, 1.644]} />
            <mesh geometry={nodes['Traversant-Porte-EXT_1'].geometry} material={materials['Menuiseries-GRIS']} position={[38.531, 1.135, -2.234]} rotation={[0, -1.57, 0]} />
            <mesh geometry={nodes['Traversant-Porte-EXT001'].geometry} material={materials['Menuiseries-GRIS']} position={[28.055, 1.135, -2.234]} rotation={[0, -1.57, 0]} />
            <mesh geometry={nodes['Traversant-Porte-EXT002'].geometry} material={materials['Menuiseries-GRIS']} position={[9.004, 1.135, -2.234]} rotation={[0, -1.57, 0]} />
            <mesh geometry={nodes['Traversant-Porte-EXT003'].geometry} material={materials['Menuiseries-GRIS']} position={[-10.064, 1.135, -2.234]} rotation={[0, -1.57, 0]} />
            <mesh geometry={nodes['Traversant-Porte-EXT004'].geometry} material={materials['Menuiseries-GRIS']} position={[-18.798, 1.135, -2.234]} rotation={[0, -1.57, 0]} />
            <mesh geometry={nodes['Traversant-Porte-EXT005'].geometry} material={materials['Menuiseries-GRIS']} position={[-24.104, 1.135, -2.234]} rotation={[0, -1.57, 0]} />
            <mesh geometry={nodes.Vitre.geometry} material={materials.Glass} position={[35.112, 1.141, -0.126]} />
            <mesh geometry={nodes.Vitre001.geometry} material={materials.Glass} position={[24.157, 1.141, -0.126]} />
            <mesh geometry={nodes.Vitre002.geometry} material={materials.Glass} position={[5.078, 1.141, -0.126]} />
            <mesh geometry={nodes.Vitre003.geometry} material={materials.Glass} position={[-13.981, 1.141, -0.126]} />
            <mesh geometry={nodes.Vitre004.geometry} material={materials.Glass} position={[-8.499, 1.141, 1.418]} />
            <mesh geometry={nodes.Vitre005.geometry} material={materials.Glass} position={[10.581, 1.141, 1.418]} />
            <mesh geometry={nodes.Vitre006.geometry} material={materials.Glass} position={[29.649, 1.141, 1.418]} />
            <mesh geometry={nodes.Vitre007.geometry} material={materials.Glass} position={[-17.408, 1.141, -0.126]} />
            <mesh geometry={nodes.Vitre008.geometry} material={materials.Glass} position={[-22.712, 1.141, -0.126]} />
            <mesh geometry={nodes.Vitre009.geometry} material={materials.Glass} position={[-26.225, 1.141, -0.126]} />
            <mesh geometry={nodes.Vitre010.geometry} material={materials.Glass} position={[-18.306, 1.141, -0.126]} />
          </group>
          <group position={[19.342, 2.192, -25.094]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Bar-Menuiserie-Arriere'].geometry} material={materials['Menuiseries-GRIS']} position={[-2.631, 2.532, -2.192]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere_1'].geometry} material={materials['Menuiseries-GRIS']} position={[2.799, -2.586, -2.192]} rotation={[0, 0, -0.784]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere_2'].geometry} material={materials['Menuiseries-GRIS']} position={[0.019, -0.27, -0.71]} rotation={[0, 0, Math.PI / 4]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere_3'].geometry} material={materials['Menuiseries-GRIS']} position={[0.019, -0.27, 1.511]} rotation={[0, 0, Math.PI / 4]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere_4'].geometry} material={materials['Menuiseries-GRIS']} position={[1.548, -1.518, -2.192]} rotation={[0, 0, 0.824]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere_5'].geometry} material={materials['Menuiseries-GRIS']} position={[0.427, -0.479, -2.192]} rotation={[0, 0, 0.824]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere_6'].geometry} material={materials['Menuiseries-GRIS']} position={[-0.694, 0.559, -2.192]} rotation={[0, 0, 0.824]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere_7'].geometry} material={materials['Menuiseries-GRIS']} position={[-1.815, 1.597, -2.182]} rotation={[0, 0, 0.824]} />
            <mesh geometry={nodes['Bar-Vitre-Arriere'].geometry} material={materials.Glass} position={[-0.07, 0.114, -2.192]} rotation={[0, 0, -0.762]} />
          </group>
          <group position={[10.455, 2.192, -30.648]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Bar-Menuiserie-Arriere001'].geometry} material={materials['Menuiseries-GRIS']} position={[0.019, -0.27, 1.511]} rotation={[0, 0, Math.PI / 4]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere002'].geometry} material={materials['Menuiseries-GRIS']} position={[-2.631, 2.532, -2.192]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere003'].geometry} material={materials['Menuiseries-GRIS']} position={[3.552, -3.231, -2.192]} rotation={[0, 0, 0.001]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere004'].geometry} material={materials['Menuiseries-GRIS']} position={[0.019, -0.27, -0.71]} rotation={[0, 0, Math.PI / 4]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere005'].geometry} material={materials['Menuiseries-GRIS']} position={[-1.514, 1.318, -2.182]} rotation={[0, 0, 0.824]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere006'].geometry} material={materials['Menuiseries-GRIS']} position={[1.85, -1.797, -2.192]} rotation={[0, 0, 0.824]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere007'].geometry} material={materials['Menuiseries-GRIS']} position={[0.729, -0.759, -2.192]} rotation={[0, 0, 0.824]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere008'].geometry} material={materials['Menuiseries-GRIS']} position={[-0.393, 0.279, -2.192]} rotation={[0, 0, 0.824]} />
            <mesh geometry={nodes['Bar-Vitre-Arriere001'].geometry} material={materials.Glass} position={[-0.07, 0.114, -2.192]} rotation={[0, 0, -0.762]} />
          </group>
          <group position={[10.455, 6.066, -30.648]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.755]}>
            <mesh geometry={nodes['Bar-Menuiserie-Arriere009'].geometry} material={materials['Menuiseries-GRIS']} position={[0.019, -0.27, 1.511]} rotation={[0, 0, Math.PI / 4]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere010'].geometry} material={materials['Menuiseries-GRIS']} position={[-2.631, 2.532, -2.192]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere011'].geometry} material={materials['Menuiseries-GRIS']} position={[3.552, -3.231, -2.192]} rotation={[0, 0, 0.001]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere012'].geometry} material={materials['Menuiseries-GRIS']} position={[0.019, -0.27, -0.71]} rotation={[0, 0, Math.PI / 4]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere013'].geometry} material={materials['Menuiseries-GRIS']} position={[-1.514, 1.318, -2.182]} rotation={[0, 0, 0.824]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere014'].geometry} material={materials['Menuiseries-GRIS']} position={[1.85, -1.797, -2.192]} rotation={[0, 0, 0.824]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere015'].geometry} material={materials['Menuiseries-GRIS']} position={[0.729, -0.759, -2.192]} rotation={[0, 0, 0.824]} />
            <mesh geometry={nodes['Bar-Menuiserie-Arriere016'].geometry} material={materials['Menuiseries-GRIS']} position={[-0.393, 0.279, -2.192]} rotation={[0, 0, 0.824]} />
            <mesh geometry={nodes['Bar-Vitre-Arriere002'].geometry} material={materials.Glass} position={[-0.07, 0.114, -2.192]} rotation={[0, 0, -0.762]} />
          </group>
          <group position={[16.579, 0.75, -13.935]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Bar-Sol-01'].geometry} material={materials.concrete_2} position={[1.439, 0.424, -0.75]} />
          </group>
          <group position={[-19.202, 2.503, 14.577]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, -1.814, 0.036]}>
              <mesh geometry={nodes['Escalator-Base-Metal'].geometry} material={materials['Menuiseries-GRIS']} position={[-0.57, 0, -0.715]} rotation={[0, 0.522, 0]} />
              <mesh geometry={nodes['Escalator-Main-Courante'].geometry} material={materials['Menuiseries-ANTHRACITE']} position={[-0.57, -0.052, -0.507]} rotation={[0, 0.522, 0]} />
              <mesh geometry={nodes['Escalator-Module-Black'].geometry} material={materials['Menuiseries-ANTHRACITE']} position={[3.553, 0, -2.504]} rotation={[0, 0.522, 0]} />
              <mesh geometry={nodes['Escalator-Vitre'].geometry} material={materials.Glass} position={[-0.011, -0.003, 0.079]} rotation={[Math.PI / 2, 0, 0]} />
            </group>
            <group position={[0, -0.526, 0.036]}>
              <mesh geometry={nodes['Escalator-Base-Metal001'].geometry} material={materials['Menuiseries-GRIS']} position={[-0.57, 0, -0.715]} rotation={[0, 0.522, 0]} />
              <mesh geometry={nodes['Escalator-Main-Courante001'].geometry} material={materials['Menuiseries-ANTHRACITE']} position={[-0.57, -0.052, -0.507]} rotation={[0, 0.522, 0]} />
              <mesh geometry={nodes['Escalator-Module-Black001'].geometry} material={materials['Menuiseries-ANTHRACITE']} position={[3.553, 0, -2.504]} rotation={[0, 0.522, 0]} />
              <mesh geometry={nodes['Escalator-Vitre001'].geometry} material={materials.Glass} position={[-0.011, -0.003, 0.079]} rotation={[Math.PI / 2, 0, 0]} />
            </group>
            <group position={[0, 0.526, 0.036]}>
              <mesh geometry={nodes['Escalator-Base-Metal002'].geometry} material={materials['Menuiseries-GRIS']} position={[-0.57, 0, -0.715]} rotation={[0, 0.522, 0]} />
              <mesh geometry={nodes['Escalator-Main-Courante002'].geometry} material={materials['Menuiseries-ANTHRACITE']} position={[-0.57, -0.052, -0.507]} rotation={[0, 0.522, 0]} />
              <mesh geometry={nodes['Escalator-Module-Black002'].geometry} material={materials['Menuiseries-ANTHRACITE']} position={[3.553, 0, -2.504]} rotation={[0, 0.522, 0]} />
              <mesh geometry={nodes['Escalator-Vitre002'].geometry} material={materials.Glass} position={[-0.011, -0.003, 0.079]} rotation={[Math.PI / 2, 0, 0]} />
            </group>
            <group position={[0, 1.814, 0.036]}>
              <mesh geometry={nodes['Escalator-Base-Metal003'].geometry} material={materials['Menuiseries-GRIS']} position={[-0.57, 0, -0.715]} rotation={[0, 0.522, 0]} />
              <mesh geometry={nodes['Escalator-Main-Courante003'].geometry} material={materials['Menuiseries-ANTHRACITE']} position={[-0.57, -0.052, -0.507]} rotation={[0, 0.522, 0]} />
              <mesh geometry={nodes['Escalator-Module-Black003'].geometry} material={materials['Menuiseries-ANTHRACITE']} position={[3.553, 0, -2.504]} rotation={[0, 0.522, 0]} />
              <mesh geometry={nodes['Escalator-Vitre003'].geometry} material={materials.Glass} position={[-0.011, -0.003, 0.079]} rotation={[Math.PI / 2, 0, 0]} />
            </group>
            <mesh geometry={nodes['Escalator-Marches'].geometry} material={materials.Chrome} position={[3.37, 0.614, -2.708]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes['Escalator-Marches001'].geometry} material={materials.Chrome} position={[3.37, -1.711, -2.708]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes['Escalator-Shell'].geometry} material={materials.Chrome} position={[3.851, -0.231, -2.511]} />
            <mesh geometry={nodes.Object004.geometry} material={materials.Chrome} position={[-0.102, -0.022, -0.124]} rotation={[0, 0.522, 0]} />
          </group>
          <group position={[17.071, 1.304, -1.846]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Escalier-Bar-Main-Courante'].geometry} material={materials['Menuiseries-GRIS']} position={[0, -0.608, -0.815]} />
            <mesh geometry={nodes['Escalier-Bar-Main-Courante001'].geometry} material={materials['Menuiseries-GRIS']} position={[0, 0.49, -0.306]} />
          </group>
          <group position={[12.668, 1.304, -8.143]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
            <mesh geometry={nodes['Escalier-Bar-Main-Courante002'].geometry} material={materials['Menuiseries-GRIS']} position={[0, -0.608, -0.815]} />
            <mesh geometry={nodes['Escalier-Bar-Main-Courante004'].geometry} material={materials['Menuiseries-GRIS']} position={[0, 0.376, -0.312]} />
          </group>
          <group position={[-16.868, 4.889, -0.572]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Garde-Corps-Rampe_1'].geometry} material={materials.concrete_2} position={[0.093, -2.569, 0.27]} />
            <mesh geometry={nodes['Garde-Corps-Vitre_1'].geometry} material={materials.concrete_2} position={[0.093, -2.569, -0.27]} />
          </group>
          <group position={[3.914, 5.386, -1.321]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['BOX-GRAND-PLAFOND'].geometry} material={materials['Material #13']} position={[7.907, 24.469, 5.054]} scale={[1.041, 1, 1]} />
          </group>
          <group position={[-11.246, 3.867, 0.786]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Plafond-Plaque-Blanc218'].geometry} material={materials['Ceiling white']} position={[20.297, 33.248, -0.032]} />
          </group>
          <group position={[34.546, 4.033, 22.462]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Plafond-Plaque-Blanc'].geometry} material={materials['Ceiling white']} position={[8.475, -9.601, 0.089]} />
          </group>
          <group position={[20.72, 3.919, -5.858]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <mesh geometry={nodes.Box300.geometry} material={materials.wood_1} position={[6.148, 2.064, -0.157]} />
          </group>
          <group position={[1.366, 3.919, 27.52]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Box061.geometry} material={materials.wood_1} position={[2.05, 4.579, -0.157]} />
          </group>
          <group position={[-17.091, 6.18, -8.233]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Box201.geometry} material={materials.concrete_2} position={[17.909, 2.996, -7.368]} rotation={[0, 0, Math.PI / 4]} />
            <mesh geometry={nodes.Box202.geometry} material={materials.concrete_2} position={[17.324, 0.783, -7.368]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteau-Beton027_1'].geometry} material={materials.concrete_2} position={[7.966, -12.995, -7.859]} />
            <mesh geometry={nodes['Poteau-Beton028'].geometry} material={materials.concrete_2} position={[-7.614, -12.995, -7.859]} />
            <mesh geometry={nodes['Poteau-Beton029'].geometry} material={materials.concrete_2} position={[16.017, -5.759, -7.859]} rotation={[0, 0, Math.PI / 4]} />
            <mesh geometry={nodes['Poteau-Structure'].geometry} material={materials.concrete_2} position={[-15.634, -5.759, -7.859]} rotation={[Math.PI, 0, Math.PI / 4]} scale={-1} />
            <mesh geometry={nodes['Poteau-Structure001'].geometry} material={materials['CONCRETE RUDE']} position={[-14.678, 4.682, -7.859]} rotation={[0, 0, Math.PI / 4]} />
            <mesh geometry={nodes['Poteau-Structure002'].geometry} material={materials.concrete_2} position={[15.053, 4.682, -7.859]} rotation={[Math.PI, 0, Math.PI / 4]} scale={-1} />
            <mesh geometry={nodes['Structure-Centrale-BETON002'].geometry} material={materials['CONCRETE RUDE']} position={[-0.113, 6.002, 0.846]} rotation={[0, 0, -Math.PI]} />
            <mesh geometry={nodes['Structure-Centrale-BETON003'].geometry} material={materials.wood_3} position={[0.117, 5.961, -3.266]} rotation={[0, 0, -Math.PI]} />
            <mesh geometry={nodes['Structure-Centrale-BOIS'].geometry} material={materials.wood_3} position={[3.907, -12.947, -7.054]} />
            <mesh geometry={nodes['Structure-Centrale-BOIS001'].geometry} material={materials.wood_3} position={[16.218, -5.533, -7.054]} rotation={[0, 0, Math.PI / 4]} />
            <mesh geometry={nodes['Structure-Centrale-BOIS002'].geometry} material={materials.concrete_2} position={[-15.906, -5.533, -7.054]} rotation={[Math.PI, 0, Math.PI / 4]} scale={-1} />
            <mesh geometry={nodes['Structure-Centrale-BOIS003'].geometry} material={materials.concrete_2} position={[3.907, -12.947, -2.287]} />
            <mesh geometry={nodes['Structure-Centrale-BOIS004'].geometry} material={materials.concrete_2} position={[16.218, -5.533, -2.287]} rotation={[0, 0, Math.PI / 4]} />
            <mesh geometry={nodes['Structure-Centrale-BOIS005'].geometry} material={materials.concrete_2} position={[-15.906, -5.533, -2.287]} rotation={[Math.PI, 0, Math.PI / 4]} scale={-1} />
            <mesh geometry={nodes['Structure-Centrale-BOIS006'].geometry} material={materials.concrete_2} position={[16.567, 5.38, -7.054]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes['Structure-Centrale-BOIS007'].geometry} material={materials.concrete_2} position={[-16.128, 5.38, -7.054]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes['Structure-Centrale-BOIS008'].geometry} material={materials.concrete_2} position={[16.567, 5.38, -1.809]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes['Structure-Centrale-BOIS009'].geometry} material={materials.concrete_2} position={[-16.128, 5.38, -2.088]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes['Structure-Centrale-BOIS010'].geometry} material={materials.concrete_2} position={[16.567, 10.391, -7.054]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes['Structure-Centrale-Support-Bois'].geometry} material={materials.concrete_2} position={[0.333, -12.833, -6.963]} />
            <mesh geometry={nodes['Structure-Centrale-Support-Metal'].geometry} material={materials.concrete_2} position={[0.334, -13.124, -6.963]} />
          </group>
          <group position={[-33.959, 1.902, 15.874]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 1.018]}>
            <mesh geometry={nodes['Menuiserie-Vitre-FOND'].geometry} material={materials['Menuiseries-GRIS']} position={[4.138, -4.033, 1.832]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Menuiserie-Vitre-FOND_1'].geometry} material={materials['Menuiseries-GRIS']} position={[4.138, -4.033, -1.972]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND'].geometry} material={materials['Menuiseries-GRIS']} position={[9.878, -9.791, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND001'].geometry} material={materials['Menuiseries-GRIS']} position={[8.278, -8.191, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND002'].geometry} material={materials['Menuiseries-GRIS']} position={[6.685, -6.583, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND003'].geometry} material={materials['Menuiseries-GRIS']} position={[5.081, -4.988, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND004'].geometry} material={materials['Menuiseries-GRIS']} position={[3.486, -3.383, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND005'].geometry} material={materials['Menuiseries-GRIS']} position={[1.887, -1.782, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND006'].geometry} material={materials['Menuiseries-GRIS']} position={[0.284, -0.186, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND007'].geometry} material={materials['Menuiseries-GRIS']} position={[-1.305, 1.425, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND008'].geometry} material={materials['Menuiseries-GRIS']} position={[-2.152, 3.742, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND009'].geometry} material={materials['Menuiseries-GRIS']} position={[-3.776, 5.367, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND010'].geometry} material={materials['Menuiseries-GRIS']} position={[-5.444, 7.019, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND011'].geometry} material={materials['Menuiseries-GRIS']} position={[-7.704, 7.033, -1.902]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND021'].geometry} material={materials['Menuiseries-GRIS']} position={[-9.849, 7.072, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND022'].geometry} material={materials['Menuiseries-GRIS']} position={[-9.849, 9.841, -1.902]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND023'].geometry} material={materials['Menuiseries-GRIS']} position={[-2.098, 2.222, -1.902]} rotation={[0, 0, -1.396]} />
            <mesh geometry={nodes['Vitre-Vitre-FOND007'].geometry} material={materials.Glass} position={[-3.261, 3.351, 0.86]} />
          </group>
          <group position={[-33.959, 5.684, 15.874]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.781]}>
            <mesh geometry={nodes['Menuiserie-Vitre-FOND001'].geometry} material={materials['Menuiseries-GRIS']} position={[4.138, -4.033, -1.972]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Menuiserie-Vitre-FOND002'].geometry} material={materials['Menuiseries-GRIS']} position={[4.138, -4.033, 1.832]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND024'].geometry} material={materials['Menuiseries-GRIS']} position={[9.878, -9.791, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND025'].geometry} material={materials['Menuiseries-GRIS']} position={[8.278, -8.191, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND026'].geometry} material={materials['Menuiseries-GRIS']} position={[6.685, -6.583, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND027'].geometry} material={materials['Menuiseries-GRIS']} position={[5.081, -4.988, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND028'].geometry} material={materials['Menuiseries-GRIS']} position={[3.486, -3.383, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND029'].geometry} material={materials['Menuiseries-GRIS']} position={[1.887, -1.782, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND030'].geometry} material={materials['Menuiseries-GRIS']} position={[0.284, -0.186, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND031'].geometry} material={materials['Menuiseries-GRIS']} position={[-1.305, 1.425, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND032'].geometry} material={materials['Menuiseries-GRIS']} position={[-2.152, 3.742, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND033'].geometry} material={materials['Menuiseries-GRIS']} position={[-3.776, 5.367, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND034'].geometry} material={materials['Menuiseries-GRIS']} position={[-5.444, 7.019, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND035'].geometry} material={materials['Menuiseries-GRIS']} position={[-7.704, 7.033, -1.902]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND036'].geometry} material={materials['Menuiseries-GRIS']} position={[-9.849, 7.072, -1.902]} rotation={[0, 0, -Math.PI / 4]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND037'].geometry} material={materials['Menuiseries-GRIS']} position={[-9.849, 9.841, -1.902]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh geometry={nodes['Poteaux-Vitre-FOND038'].geometry} material={materials['Menuiseries-GRIS']} position={[-2.098, 2.222, -1.902]} rotation={[0, 0, -1.396]} />
            <mesh geometry={nodes['Vitre-Vitre-FOND008'].geometry} material={materials.Glass} position={[-3.261, 3.351, 0.86]} />
          </group>
          <mesh geometry={nodes.Box021.geometry} material={materials['Menuiseries-ANTHRACITE']} position={[30.655, 4.122, 22.162]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Box117.geometry} material={materials.wood_2} position={[22.052, 0, 4.326]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Box118.geometry} material={materials.wood_2} position={[-8.38, 0, 26.11]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Box195.geometry} material={materials.concrete_2} position={[2.416, -1.39, -2.386]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Box196.geometry} material={materials.concrete_2} position={[-10.298, -0.684, 3.579]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Box197.geometry} material={materials.concrete_2} position={[-21.999, -0.684, 5.087]} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
          <mesh geometry={nodes.Box198.geometry} material={materials['CONCRETE RUDE']} position={[-36.202, -1.39, -2.386]} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
          <mesh geometry={nodes.Box199.geometry} material={materials.concrete_2} position={[4.811, -1.39, -13.879]} rotation={[-Math.PI / 2, 0, Math.PI / 4]} />
          <mesh geometry={nodes.Box200.geometry} material={materials.concrete_2} position={[3.646, -0.737, -19.52]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Box203.geometry} material={materials.concrete_2} position={[14.136, 0, -15.587]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Box204.geometry} material={materials['Default-Material']} position={[19.826, 0, -27.487]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Box205.geometry} material={materials.WOOD} position={[14.115, 0, -23.484]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Box305.geometry} material={materials.wood_2} position={[-43.855, 0, 2.216]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Box306.geometry} material={materials.concrete_2} position={[-41.785, 0, -5.448]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Box307.geometry} material={materials.concrete_2} position={[-38.471, -0.481, -3.601]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Box308.geometry} material={materials.WOOD} position={[-43.855, 4.752, 2.216]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Box310.geometry} material={materials['Default-Material']} position={[-43.862, 8.339, 2.216]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Box311.geometry} material={materials.WOOD} position={[-43.855, 4.587, 2.216]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Box312.geometry} material={materials.WOOD} position={[19.467, 4.183, -27.269]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Box313.geometry} material={materials.WOOD} position={[9.485, 4.183, -31.18]} rotation={[-Math.PI / 2, 0, -Math.PI / 4]} />
          <mesh geometry={nodes.Box314.geometry} material={materials.concrete_2} position={[5.009, -0.692, -3.635]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Box316.geometry} material={materials.concrete_2} position={[-23.568, 3.39, 14.608]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Cache-Plafond-3EME'].geometry} material={materials['Menuiseries-ANTHRACITE']} position={[10.992, 6.601, -0.263]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Cache-Plafond-3m75'].geometry} material={materials['Menuiseries-Noire']} position={[10.006, 3.89, 19.173]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Cache-Plafond-4M10'].geometry} material={materials['Menuiseries-Noire']} position={[29.618, 4.221, 22.243]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Line001.geometry} material={materials.concrete_2} position={[-17.024, 3.981, 1.705]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Line003.geometry} material={materials.concrete_2} position={[-4.47, 7.418, 1.705]} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
          <mesh geometry={nodes['Poteau-Beton'].geometry} material={materials.concrete_1} position={[38.521, -0.007, 28.019]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton001'].geometry} material={materials.concrete_1} position={[30.573, -0.007, 28.019]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton002'].geometry} material={materials.concrete_1} position={[22.625, -0.007, 28.019]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton003'].geometry} material={materials.concrete_1} position={[14.677, -0.008, 28.019]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton004'].geometry} material={materials.concrete_2} position={[6.729, -0.008, 28.019]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton005'].geometry} material={materials.concrete_2} position={[-1.218, -0.008, 28.019]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton009'].geometry} material={materials.concrete_1} position={[14.677, -0.008, 20.003]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton010'].geometry} material={materials.concrete_2} position={[6.729, -0.008, 20.003]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton011'].geometry} material={materials.concrete_2} position={[-1.218, -0.008, 20.003]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Cube.geometry} material={materials['Ceiling white']} position={[0, 0, 3]} scale={[1.869, 0.577, 1.331]} />
          </mesh>
          <mesh geometry={nodes['Poteau-Beton012'].geometry} material={materials.concrete_2} position={[-9.166, -0.008, 20.003]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton013'].geometry} material={materials.concrete_2} position={[-17.114, -0.008, 20.003]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton014'].geometry} material={materials.concrete_2} position={[-25.062, -0.008, 20.003]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton015'].geometry} material={materials.concrete_1} position={[14.677, -0.008, 12.066]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton016'].geometry} material={materials.concrete_2} position={[6.729, -0.008, 12.066]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton017'].geometry} material={materials.concrete_2} position={[-1.218, -0.008, 12.066]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton020'].geometry} material={materials['CONCRETE RUDE']} position={[-25.062, -0.008, 12.066]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton021'].geometry} material={materials.concrete_2} position={[14.677, -0.008, 4.124]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton022'].geometry} material={materials.concrete_2} position={[6.729, -0.008, 4.124]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton024'].geometry} material={materials['CONCRETE RUDE']} position={[-32.768, -0.008, 12.066]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton025'].geometry} material={materials.concrete_2} position={[6.729, -0.008, -3.692]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton026'].geometry} material={materials.concrete_2} position={[6.729, -0.008, -11.752]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton027'].geometry} material={materials.concrete_2} position={[-1.072, 0, -19.002]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton030'].geometry} material={materials.concrete_2} position={[14.677, -0.008, -3.719]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Poteau-Beton031'].geometry} material={materials.concrete_2} position={[-40.701, -0.008, 4.158]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Sol.geometry} material={materials.green_fabric} position={[1.477, 0, 2.141]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Sol_-1'].geometry} material={materials.concrete_2} position={[-16.767, -0.676, -5.296]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Sol-Plafond-1'].geometry} material={materials.concrete_2} position={[18.66, 6.43, 2.47]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Stairs-Mini'].geometry} material={materials.concrete_2} position={[-16.497, -0.551, 8.471]} rotation={[-Math.PI / 2, 0, -1.571]} scale={[1, 1, 0.796]} />
          <mesh geometry={nodes['Stairs-Mini001'].geometry} material={materials.concrete_2} position={[-3.724, -0.551, 5.222]} rotation={[-Math.PI / 2, 0, 2.36]} scale={[1, 1, 0.796]} />
          <mesh geometry={nodes['Stairs-Mini002'].geometry} material={materials['CONCRETE RUDE']} position={[-28.646, -0.551, 6.663]} rotation={[-Math.PI / 2, 0, -2.36]} scale={[-1, -1, -0.796]} />
          <mesh geometry={nodes['Stairs-Mini003'].geometry} material={materials.concrete_2} position={[3.23, -0.551, -4.286]} rotation={[-Math.PI / 2, 0, 3.141]} scale={[1, 1, 0.796]} />
          <mesh geometry={nodes['Stairs-Mini004'].geometry} material={materials.concrete_2} position={[-36.919, -0.551, -4.286]} rotation={[-Math.PI / 2, 0, 3.141]} scale={[1, 1, 0.796]} />
          <mesh geometry={nodes.StraightStair001.geometry} material={materials.concrete_2} position={[-39.765, -0.026, 4.447]} rotation={[-Math.PI / 2, 0, 1.57]} scale={[1.06, 1, 1]} />
          <mesh geometry={nodes['Traversant-Porte-EXT'].geometry} material={materials['Menuiseries-GRIS']} position={[57.839, 4.19, 32.335]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
          <group position={[1.762, 1.371, 30.993]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-0.013, -0.003, -0.121]}>
              <group rotation={[0, 0, -2.094]}>
                <mesh geometry={nodes['Tourniquet-Vitre002'].geometry} material={materials.Glass} position={[-0.941, 0, -1.191]} />
                <mesh geometry={nodes['Tourniquet-Vitre003'].geometry} material={materials['Menuiseries-ANTHRACITE']} />
              </group>
              <group rotation={[0, 0, 2.094]}>
                <mesh geometry={nodes['Tourniquet-Vitre004'].geometry} material={materials.Glass} position={[-0.941, 0, -1.191]} />
                <mesh geometry={nodes['Tourniquet-Vitre005'].geometry} material={materials['Menuiseries-ANTHRACITE']} />
              </group>
              <mesh geometry={nodes.Cylinder002.geometry} material={materials['Default-Material']} position={[0, 0, -1.25]} />
              <mesh geometry={nodes['Tourniquet-Vitre_1'].geometry} material={materials.Glass} position={[-0.941, 0, -1.191]} />
              <mesh geometry={nodes['Tourniquet-Vitre_2'].geometry} material={materials['Menuiseries-ANTHRACITE']} />
            </group>
            <mesh geometry={nodes['Tourniquet-Montants'].geometry} material={materials['Menuiseries-ANTHRACITE']} position={[0, 0, -1.395]} />
            <mesh geometry={nodes['Tourniquet-Toit'].geometry} material={materials['Menuiseries-ANTHRACITE']} position={[0, 0, 1.127]} />
            <mesh geometry={nodes['Tourniquet-Vitre'].geometry} material={materials.Glass} position={[0.004, 0, -0.2]} />
            <mesh geometry={nodes['Tourniquet-Vitre001'].geometry} material={materials.Glass} position={[0.004, 0, -0.2]} rotation={[0, 0, Math.PI]} />
          </group>
          <group position={[-3.565, 1.371, 30.993]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-0.013, -0.003, -0.121]} rotation={[0, 0, Math.PI / 4]}>
              <group rotation={[0, 0, -2.094]}>
                <mesh geometry={nodes['Tourniquet-Vitre010'].geometry} material={materials.Glass} position={[-0.941, 0, -1.191]} />
                <mesh geometry={nodes['Tourniquet-Vitre011'].geometry} material={materials['Menuiseries-ANTHRACITE']} />
              </group>
              <group rotation={[0, 0, 2.094]}>
                <mesh geometry={nodes['Tourniquet-Vitre012'].geometry} material={materials.Glass} position={[-0.941, 0, -1.191]} />
                <mesh geometry={nodes['Tourniquet-Vitre013'].geometry} material={materials['Menuiseries-ANTHRACITE']} />
              </group>
              <mesh geometry={nodes.Cylinder003.geometry} material={materials['Default-Material']} position={[0, 0, -1.25]} />
              <mesh geometry={nodes['Tourniquet-Vitre006'].geometry} material={materials['Menuiseries-ANTHRACITE']} />
              <mesh geometry={nodes['Tourniquet-Vitre007'].geometry} material={materials.Glass} position={[-0.941, 0, -1.191]} />
            </group>
            <mesh geometry={nodes['Tourniquet-Montants001'].geometry} material={materials['Menuiseries-ANTHRACITE']} position={[0, 0, -1.395]} />
            <mesh geometry={nodes['Tourniquet-Toit001'].geometry} material={materials['Menuiseries-ANTHRACITE']} position={[0, 0, 1.127]} />
            <mesh geometry={nodes['Tourniquet-Vitre008'].geometry} material={materials.Glass} position={[0.004, 0, -0.2]} />
            <mesh geometry={nodes['Tourniquet-Vitre009'].geometry} material={materials.Glass} position={[0.004, 0, -0.2]} rotation={[0, 0, Math.PI]} />
          </group>
        </group>
        <group position={[-4.397, -0.82, 22.066]}>
          <PerspectiveCamera makeDefault={false} far={1000.134} near={0.3} fov={66.7} position={[6.865, 0.682, -32.132]} rotation={[3.077, -0.025, 3.14]} />
        </group>
        <group position={[-12.897, -0.572, 29.178]}>
          <group position={[21.474, 0, -35.31]}>
            <mesh geometry={nodes.Sphere_light.geometry} material={materials['SphereLight Low']} position={[-1.537, 1.026, -3.201]} scale={0.107} />
            <mesh geometry={nodes['Sphere_light_(1)'].geometry} material={materials['SphereLight Low']} position={[-1.513, 1.512, -2.591]} scale={0.124} />
            <mesh geometry={nodes['Sphere_light_(2)'].geometry} material={materials.SphereLight} position={[-1.524, 0.942, -2.161]} scale={0.111} />
            <mesh geometry={nodes['Sphere_light_(3)'].geometry} material={materials.SphereLight} position={[-1.537, 0.87, -1.68]} scale={0.109} />
            <mesh geometry={nodes['Sphere_light_(4)'].geometry} material={materials.SphereLight} position={[-1.542, 0.837, -0.293]} scale={0.124} />
            <mesh geometry={nodes['Sphere_light_(5)'].geometry} material={materials.SphereLight} position={[-1.526, 0.751, 0.484]} scale={0.124} />
            <mesh geometry={nodes['Sphere_light_(6)'].geometry} material={materials.SphereLight} position={[-1.545, 1.016, 1.078]} scale={0.124} />
            <mesh geometry={nodes['Sphere_light_(7)'].geometry} material={materials.SphereLight} position={[-1.532, 1.25, -1.29]} scale={0.107} />
            <mesh geometry={nodes['Sphere_light_(8)'].geometry} material={materials.SphereLight} position={[-1.536, 1.63, -0.945]} scale={0.063} />
            <mesh geometry={nodes['Sphere_light_(9)'].geometry} material={materials.SphereLight} position={[-1.522, 1.425, -0.68]} scale={0.063} />
            <mesh geometry={nodes['Sphere_light_(10)'].geometry} material={materials.SphereLight} position={[-1.535, 1.281, 0.104]} scale={0.063} />
            <mesh geometry={nodes['Sphere_light_(11)'].geometry} material={materials.SphereLight} position={[-0.777, 1.425, 1.359]} scale={0.063} />
            <mesh geometry={nodes['Sphere_light_(12)'].geometry} material={materials.SphereLight} position={[-1.138, 1.625, 1.357]} scale={0.063} />
          </group>
          <directionalLight intensity={0.383} decay={2} color="#eaf8ff" position={[-40, 5.3, -68.85]} rotation={[-2.67, -0.03, -3.106]} />
          <spotLight intensity={4.142} angle={1.264} penumbra={0.2} decay={2} distance={8.041} position={[10.14, 2.43, -35.35]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
          {/* <directionalLight intensity={0.885} decay={2} color="#e0e0e0" position={[-9.84, 0, -57.09]} rotation={[-Math.PI, 0, -Math.PI]} /> */}
          {/* <pointLight intensity={10.142} decay={2} distance={10} position={[20.616, 0.053, -35.524]} rotation={[-Math.PI, 0, -Math.PI]} /> */}
          {/* <directionalLight intensity={0.201} decay={2} color="#e0e0e0" position={[15.16, 1.965, -35.84]} rotation={[-1.593, 0, -Math.PI]} /> */}
          <spotLight intensity={50.42} angle={0.73} penumbra={0.2} decay={2} distance={8.041} position={[19.004, 7.4, -36.03]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
          <directionalLight intensity={0.282} decay={2} color="#e0e0e0" position={[11, 2.61, -6.55]} rotation={[-1.593, 0, -Math.PI]} />
          {/* <directionalLight intensity={1.414} decay={2} color="#e0e0e0" position={[0.464, 0, -30.35]} rotation={[-Math.PI, 0, -Math.PI]} /> */}
          <mesh geometry={nodes.Column_lightbox.geometry} material={materials.Led} position={[4.011, 2.597, -30.523]} rotation={[-Math.PI, 0, 0]} scale={[0.267, 0.2, 0.134]} />
          <mesh geometry={nodes['Column_lightbox_(3)'].geometry} material={materials.Led} position={[3.849, 2.596, -22.634]} rotation={[-Math.PI, 0, 0]} scale={[0.267, 0.2, 0.105]} />
          <mesh geometry={nodes['Column_lightbox_(4)'].geometry} material={materials.Led} position={[11.73, 2.596, -22.634]} rotation={[-Math.PI, 0, 0]} scale={[0.267, 0.2, 0.126]} />
          <mesh geometry={nodes['Column_lightbox_(5)'].geometry} material={materials.Led} position={[11.65, 2.597, -30.523]} rotation={[-Math.PI, 0, 0]} scale={[0.267, 0.2, 0.134]} />
          <mesh geometry={nodes['Column_lightbox_(6)'].geometry} material={materials.Led} position={[3.94, 2.582, -14.667]} rotation={[-Math.PI, 0, 0]} scale={[0.224, 0.2, 0.134]} />
          <mesh geometry={nodes['Column_lightbox_(7)'].geometry} material={materials.Led} position={[-3.971, 2.582, -14.667]} rotation={[-Math.PI, 0, 0]} scale={[0.224, 0.2, 0.134]} />
          <mesh geometry={nodes['Column_lightbox_(8)'].geometry} material={materials.Led} position={[-3.971, 2.582, -6.902]} rotation={[-Math.PI, 0, 0]} scale={[0.188, 0.2, 0.059]} />
          <mesh geometry={nodes['Column_lightbox_(13)'].geometry} material={materials.Led} position={[20.6, 2.597, -30.523]} rotation={[-Math.PI, 0, 0]} scale={[0.267, 0.2, 0.134]} />
          <mesh geometry={nodes['Column_lightbox_(14)'].geometry} material={materials.Led} position={[27.97, 2.597, -30.523]} rotation={[-Math.PI, 0, 0]} scale={[0.267, 0.2, 0.134]} />
          <mesh geometry={nodes['Column_lightbox_(15)'].geometry} material={materials.Led} position={[35.971, 2.597, -30.523]} rotation={[-Math.PI, 0, 0]} scale={[0.267, 0.2, 0.134]} />
          <mesh geometry={nodes['Column_lightbox_(16)'].geometry} material={materials.Led} position={[11.977, 2.488, -38.606]} rotation={[-Math.PI, 0, 0]} scale={[0.22, 0.2, 0.063]} />
          <mesh geometry={nodes['Column_lightbox_(17)'].geometry} material={materials.Led} position={[4.011, 2.488, -38.626]} rotation={[-Math.PI, 0, 0]} scale={[0.22, 0.2, 0.063]} />
          <mesh geometry={nodes['Column_lightbox_(1)'].geometry} material={materials['Led Concrete']} position={[-3.999, 2.597, -30.523]} rotation={[-Math.PI, 0, 0]} scale={[0.267, 0.2, 0.134]} />
          <mesh geometry={nodes['Column_lightbox_(2)'].geometry} material={materials['Led Concrete']} position={[-3.999, 2.596, -22.634]} rotation={[-Math.PI, 0, 0]} scale={[0.267, 0.2, 0.094]} />
          <mesh geometry={nodes['Column_lightbox_(9)'].geometry} material={materials['Led Concrete']} position={[-3.999, 2.597, -38.555]} rotation={[-Math.PI, 0, 0]} scale={[0.267, 0.2, 0.134]} />
          <mesh geometry={nodes['Column_lightbox_(10)'].geometry} material={materials['Led Concrete']} position={[-12.047, 2.872, -38.555]} rotation={[-Math.PI, 0, 0]} scale={[0.267, 0.2, 0.134]} />
          <mesh geometry={nodes['Column_lightbox_(11)'].geometry} material={materials['Led Concrete']} position={[-19.92, 2.872, -38.555]} rotation={[-Math.PI, 0, 0]} scale={[0.267, 0.2, 0.134]} />
          <mesh geometry={nodes['Column_lightbox_(12)'].geometry} material={materials['Led Concrete']} position={[-27.83, 2.872, -38.555]} rotation={[-Math.PI, 0, 0]} scale={[0.267, 0.2, 0.134]} />
          <mesh geometry={nodes.Long_led.geometry} material={materials.Led} position={[-28.62, 2.91, -39.61]} rotation={[-Math.PI, 0.001, 0]} scale={[4.27, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(1)'].geometry} material={materials.Led} position={[-21.98, 2.9, -35.51]} rotation={[-Math.PI, 0.003, 0]} scale={[4.344, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(2)'].geometry} material={materials.Led} position={[-7.241, 2.86, -31.514]} rotation={[-Math.PI, 0.003, 0]} scale={[5.633, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(3)'].geometry} material={materials.Led} position={[-7.25, 2.86, -27.41]} rotation={[-Math.PI, 0.003, 0]} scale={[4.73, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(4)'].geometry} material={materials.Led} position={[-21.39, 2.88, -23.23]} rotation={[-Math.PI, -0.002, -0.001]} scale={[2.076, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(5)'].geometry} material={materials.Led} position={[4.8, 2.58, -27.47]} rotation={[-Math.PI, 0.003, 0]} scale={[2.24, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(6)'].geometry} material={materials.Led} position={[4.78, 2.58, -23.34]} rotation={[-Math.PI, -0.002, 0]} scale={[2.24, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(7)'].geometry} material={materials.Led} position={[4.81, 2.58, -31.47]} rotation={[-Math.PI, 0.003, 0]} scale={[2.24, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(8)'].geometry} material={materials.Led} position={[-0.28, 2.58, -19.19]} rotation={[-Math.PI, -0.004, 0]} scale={[2.137, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(9)'].geometry} material={materials.Led} position={[-2.18, 2.58, -15.07]} rotation={[-Math.PI, -0.004, 0]} scale={[1.805, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(10)'].geometry} material={materials.Led} position={[-3.88, 2.58, -10.82]} rotation={[-Math.PI, -0.004, 0]} scale={[1.395, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(11)'].geometry} material={materials.Led} position={[5.393, 2.58, -34.723]} rotation={[-Math.PI, 0.003, 0]} scale={[0.1, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(12)'].geometry} material={materials.Led} position={[8.35, 2.58, -36.038]} rotation={[-Math.PI, 0.003, 0]} scale={[0.1, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(13)'].geometry} material={materials.Led} position={[12.61, 2.58, -36.03]} rotation={[-Math.PI, 0.003, 0]} scale={[0.1, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(14)'].geometry} material={materials.Led} position={[16.62, 2.58, -36.037]} rotation={[-Math.PI, 0.003, 0]} scale={[0.1, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(15)'].geometry} material={materials.Led} position={[16.63, 2.58, -38.67]} rotation={[-Math.PI, 0.003, 0]} scale={[0.1, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(16)'].geometry} material={materials.Led} position={[16.64, 2.58, -41.172]} rotation={[-Math.PI, 0.003, 0]} scale={[0.1, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(17)'].geometry} material={materials.Led} position={[12.38, 2.58, -41.166]} rotation={[-Math.PI, 0.003, 0]} scale={[0.1, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(18)'].geometry} material={materials.Led} position={[6.4, 2.58, -41.18]} rotation={[-Math.PI, 0.003, 0]} scale={[0.1, 0.2, 0.01]} />
          <mesh geometry={nodes['Long_led_(19)'].geometry} material={materials.Led} position={[27.63, 2.58, -31.49]} rotation={[-Math.PI, 0.002, 0]} scale={[2.24, 0.2, 0.01]} />
        </group>
        <mesh geometry={nodes.VideoPlane.geometry} material={materials.VideoMaterial} position={[8.883, -0.042, -6.84]} rotation={[1.571, 0, 1.571]} scale={[0.234, 0.131, 0.11]} />
        <mesh geometry={nodes.Outside_view.geometry} material={materials.Outside} position={[-21.087, 5.418, -24.81]} rotation={[Math.PI / 2, 0, 0]} scale={[9.057, 1, 3.37]} />
      </group>
    </group>
  )
}

useGLTF.preload('/_3DOffice.glb')
