/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 BossAvatar.glb
*/

import React, { useRef,useEffect, useCallback } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model10(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/BossAvatar.glb')
  const { actions } = useAnimations(animations, group)
  
    //var from = animationName === "talk" ? 'Armature.003|mixamo.com|Layer0.001' : 'Armature.001|mixamo.com|Layer0.001';
    //var to = animationName === "talk" ? 'Armature.001|mixamo.com|Layer0.001' : 'Armature.003|mixamo.com|Layer0.001';
    // if (actions[from].isRunning()) {
    //   actions[from].fadeOut(0.3);
    // }

  const handleAnimation = useCallback((animationName) => {
    if (animationName === 'talk') {
      actions['Armature|mixamo.com|Layer0'].stop(); // idle animation
      actions['Armature.001|mixamo.com|Layer0'].reset().fadeIn(0.3).play(); // talking animation
    } else {
      actions['Armature.001|mixamo.com|Layer0'].stop(); // talking animation
      actions['Armature|mixamo.com|Layer0'].reset().fadeIn(0.3).play(); // idle animation
    }
  }, [actions]);
  useEffect(() => {
    handleAnimation(props.animationName);
  }, [props.animationName, handleAnimation]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Hips} />
          <skinnedMesh name="Wolf3D_Body" geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
          <skinnedMesh name="Wolf3D_Hair" geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Bottom" geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Footwear" geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Top" geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
          <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
          <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/BossAvatar.glb')
